# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Ingrese el nombre', max_length=50)),
                ('Telefono', models.CharField(help_text='Ingrese el nombre', max_length=10)),
                ('Sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], help_text='Seleccione el sexo', max_length=1)),
                ('Fecha_Nacimiento', models.DateField(help_text='Coloque la fecha de nacimiento')),
            ],
        ),
    ]
